# -*- coding: utf-8 -*-
"""FastRCNN_Spring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fc5US9fsKQ_gCBEnBrbugsXZWvHS4hDE
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q torchmetrics

from pathlib import Path
import random
import xml.etree.ElementTree as ET
from collections import defaultdict

import albumentations as A
import matplotlib.pyplot as plt
import numpy as np
import torch
import torchvision

from albumentations.pytorch import ToTensorV2
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchmetrics.detection.mean_ap import MeanAveragePrecision
from torchvision.models.detection import (
    fasterrcnn_resnet50_fpn_v2,
    FasterRCNN_ResNet50_FPN_V2_Weights
)
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.ops import box_iou
from torchvision.utils import draw_bounding_boxes
from tqdm.auto import tqdm

# =========================
# Config
# =========================

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
NUM_CLASSES = 3  # background + dead + live

CLASS_NAME_TO_ID = {
    "live": 1,
    "dead": 2,
}

CLASS_ID_TO_NAME = {
    1: "live",
    2: "dead",
}

BATCH_SIZE = 4
NUM_WORKERS = 2
NUM_EPOCHS = 10
LR = 1e-4
WEIGHT_DECAY = 1e-4

IMAGE_SIZE = 640

# Update this root path
DATA_ROOT = Path("/content/drive/MyDrive/Capstone/Mussel Dataset 1 - RCNN_SSD")

TRAIN_IMAGES = DATA_ROOT / "train" / "images"
TRAIN_LABELS = DATA_ROOT / "train" / "labels"

VAL_IMAGES = DATA_ROOT / "valid" / "images"
VAL_LABELS = DATA_ROOT / "valid" / "labels"

TEST_IMAGES = DATA_ROOT / "test" / "images"
TEST_LABELS = DATA_ROOT / "test" / "labels"

MODEL_SAVE_PATH = DATA_ROOT / "fasterrcnn_best.pth"

def collate_fn(batch):
    return tuple(zip(*batch))


def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


set_seed(42)

def parse_voc_xml(xml_path: Path, class_name_to_id: dict):
    """
    Parse a Pascal VOC XML file into boxes and labels.

    Parameters:
        - xml_path : Path
            Path to the XML annotation file.
        - class_name_to_id : dict
            Mapping from class names to integer IDs.

    Returns:
        - boxes : list[list[float]]
            Bounding boxes in [xmin, ymin, xmax, ymax] format.
        - labels : list[int]
            Integer class labels.
    """
    tree = ET.parse(xml_path)
    root = tree.getroot()

    boxes = []
    labels = []

    for obj in root.findall("object"):
        class_name = obj.find("name").text.strip().lower()

        if class_name not in class_name_to_id:
            continue

        bndbox = obj.find("bndbox")
        xmin = float(bndbox.find("xmin").text)
        ymin = float(bndbox.find("ymin").text)
        xmax = float(bndbox.find("xmax").text)
        ymax = float(bndbox.find("ymax").text)

        if xmax <= xmin or ymax <= ymin:
            continue

        boxes.append([xmin, ymin, xmax, ymax])
        labels.append(class_name_to_id[class_name])

    return boxes, labels

def get_train_transforms():
    return A.Compose(
        [
            A.Resize(IMAGE_SIZE, IMAGE_SIZE),
            A.HorizontalFlip(p=0.5),
            A.Rotate(limit=15, p=0.5, border_mode=0),
            A.RandomBrightnessContrast(p=0.3),
            A.Affine(scale=(0.95, 1.05), translate_percent=(0.0, 0.05), p=0.3),
            ToTensorV2(),
        ],
        bbox_params=A.BboxParams(
            format="pascal_voc",
            label_fields=["labels"],
            min_visibility=0.1
        )
    )


def get_eval_transforms():
    return A.Compose(
        [
            A.Resize(IMAGE_SIZE, IMAGE_SIZE),
            ToTensorV2(),
        ],
        bbox_params=A.BboxParams(
            format="pascal_voc",
            label_fields=["labels"],
            min_visibility=0.0
        )
    )

class VOCDataset(Dataset):
    """
    PyTorch Dataset for Pascal VOC object detection.

    Parameters:
        - images_dir : Path
            Directory containing image files.
        - labels_dir : Path
            Directory containing Pascal VOC XML files.
        - class_name_to_id : dict
            Mapping from class names to integer IDs.
        - transforms : callable or None
            Albumentations transform pipeline.

    Returns:
        - image : torch.Tensor
            Image tensor of shape [C, H, W].
        - target : dict
            Detection target dictionary expected by torchvision detection models.
    """

    def __init__(self, images_dir, labels_dir, class_name_to_id, transforms=None):
        self.images_dir = Path(images_dir)
        self.labels_dir = Path(labels_dir)
        self.class_name_to_id = class_name_to_id
        self.transforms = transforms

        valid_exts = {".jpg", ".jpeg", ".png", ".bmp"}
        self.image_paths = sorted([p for p in self.images_dir.iterdir() if p.suffix.lower() in valid_exts])

        self.samples = []
        for img_path in self.image_paths:
            xml_path = self.labels_dir / f"{img_path.stem}.xml"
            if xml_path.exists():
                self.samples.append((img_path, xml_path))

        print(f"Loaded {len(self.samples)} samples from {self.images_dir}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, xml_path = self.samples[idx]

        image = np.array(Image.open(img_path).convert("RGB"))
        boxes, labels = parse_voc_xml(xml_path, self.class_name_to_id)

        boxes_np = np.array(boxes, dtype=np.float32) if len(boxes) > 0 else np.zeros((0, 4), dtype=np.float32)
        labels_np = np.array(labels, dtype=np.int64) if len(labels) > 0 else np.zeros((0,), dtype=np.int64)

        if self.transforms is not None:
            transformed = self.transforms(
                image=image,
                bboxes=boxes_np.tolist(),
                labels=labels_np.tolist()
            )
            image = transformed["image"]

            if len(transformed["bboxes"]) > 0:
                boxes_np = np.array(transformed["bboxes"], dtype=np.float32)
                labels_np = np.array(transformed["labels"], dtype=np.int64)
            else:
                boxes_np = np.zeros((0, 4), dtype=np.float32)
                labels_np = np.zeros((0,), dtype=np.int64)
        else:
            image = ToTensorV2()(image=image)["image"]

        # Always enforce correct dtype/range here
        if image.dtype != torch.float32:
            image = image.float()

        if image.max() > 1.0:
            image = image / 255.0

        boxes_tensor = torch.as_tensor(boxes_np, dtype=torch.float32)
        labels_tensor = torch.as_tensor(labels_np, dtype=torch.int64)

        area = (
            (boxes_tensor[:, 2] - boxes_tensor[:, 0]) *
            (boxes_tensor[:, 3] - boxes_tensor[:, 1])
        ) if len(boxes_tensor) > 0 else torch.zeros((0,), dtype=torch.float32)

        iscrowd = torch.zeros((len(labels_tensor),), dtype=torch.int64)

        target = {
            "boxes": boxes_tensor,
            "labels": labels_tensor,
            "image_id": torch.tensor([idx]),
            "area": area,
            "iscrowd": iscrowd,
        }

        return image, target

train_dataset = VOCDataset(
    images_dir=TRAIN_IMAGES,
    labels_dir=TRAIN_LABELS,
    class_name_to_id=CLASS_NAME_TO_ID,
    transforms=get_train_transforms()
)

val_dataset = VOCDataset(
    images_dir=VAL_IMAGES,
    labels_dir=VAL_LABELS,
    class_name_to_id=CLASS_NAME_TO_ID,
    transforms=get_eval_transforms()
)

test_dataset = VOCDataset(
    images_dir=TEST_IMAGES,
    labels_dir=TEST_LABELS,
    class_name_to_id=CLASS_NAME_TO_ID,
    transforms=get_eval_transforms()
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    collate_fn=collate_fn
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    collate_fn=collate_fn
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    collate_fn=collate_fn
)

def get_model(num_classes: int):
    weights = FasterRCNN_ResNet50_FPN_V2_Weights.DEFAULT
    model = fasterrcnn_resnet50_fpn_v2(weights=weights)

    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)

    return model


model = get_model(NUM_CLASSES).to(DEVICE)

params = [p for p in model.parameters() if p.requires_grad]

optimizer = torch.optim.AdamW(
    params,
    lr=LR,
    weight_decay=WEIGHT_DECAY
)

scheduler = torch.optim.lr_scheduler.StepLR(
    optimizer,
    step_size=5,
    gamma=0.1
)

def train_one_epoch(model, loader, optimizer, device):
    model.train()
    running_loss = 0.0

    pbar = tqdm(loader, desc="Training", leave=False)

    for images, targets in pbar:
        images = [img.to(device) for img in images]
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

        loss_dict = model(images, targets)
        loss = sum(loss for loss in loss_dict.values())

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        pbar.set_postfix(loss=f"{loss.item():.4f}")

    return running_loss / max(len(loader), 1)

@torch.no_grad()
def evaluate_map(model, loader, device):
    model.eval()

    metric = MeanAveragePrecision(
        box_format="xyxy",
        iou_type="bbox",
        class_metrics=True
    ).to(device)

    for images, targets in tqdm(loader, desc="Evaluating mAP", leave=False):
        images = [img.to(device) for img in images]
        outputs = model(images)

        preds = []
        gts = []

        for output, target in zip(outputs, targets):
            preds.append({
                "boxes": output["boxes"].detach().to(device),
                "scores": output["scores"].detach().to(device),
                "labels": output["labels"].detach().to(device),
            })

            gts.append({
                "boxes": target["boxes"].to(device),
                "labels": target["labels"].to(device),
            })

        metric.update(preds, gts)

    results = metric.compute()
    return results

@torch.no_grad()
def evaluate_classwise_metrics(
    model,
    loader,
    device,
    iou_thresh=0.5,
    score_thresh=0.5,
    class_id_to_name=None
):
    model.eval()

    stats = {
        class_id: {"tp": 0, "fp": 0, "fn": 0}
        for class_id in class_id_to_name.keys()
    }

    for images, targets in tqdm(loader, desc="Evaluating class-wise", leave=False):
        images = [img.to(device) for img in images]
        outputs = model(images)

        for output, target in zip(outputs, targets):
            pred_boxes = output["boxes"].detach().cpu()
            pred_scores = output["scores"].detach().cpu()
            pred_labels = output["labels"].detach().cpu()

            gt_boxes = target["boxes"].cpu()
            gt_labels = target["labels"].cpu()

            keep = pred_scores >= score_thresh
            pred_boxes = pred_boxes[keep]
            pred_labels = pred_labels[keep]

            for class_id in class_id_to_name.keys():
                pred_mask = pred_labels == class_id
                gt_mask = gt_labels == class_id

                cls_pred_boxes = pred_boxes[pred_mask]
                cls_gt_boxes = gt_boxes[gt_mask]

                if len(cls_pred_boxes) == 0 and len(cls_gt_boxes) == 0:
                    continue

                if len(cls_pred_boxes) == 0:
                    stats[class_id]["fn"] += len(cls_gt_boxes)
                    continue

                if len(cls_gt_boxes) == 0:
                    stats[class_id]["fp"] += len(cls_pred_boxes)
                    continue

                ious = box_iou(cls_pred_boxes, cls_gt_boxes)

                matched_gt = set()
                matched_pred = set()

                candidate_pairs = []
                for pred_idx in range(ious.shape[0]):
                    for gt_idx in range(ious.shape[1]):
                        iou_val = ious[pred_idx, gt_idx].item()
                        if iou_val >= iou_thresh:
                            candidate_pairs.append((iou_val, pred_idx, gt_idx))

                candidate_pairs.sort(reverse=True, key=lambda x: x[0])

                for _, pred_idx, gt_idx in candidate_pairs:
                    if pred_idx not in matched_pred and gt_idx not in matched_gt:
                        matched_pred.add(pred_idx)
                        matched_gt.add(gt_idx)

                tp = len(matched_pred)
                fp = len(cls_pred_boxes) - tp
                fn = len(cls_gt_boxes) - len(matched_gt)

                stats[class_id]["tp"] += tp
                stats[class_id]["fp"] += fp
                stats[class_id]["fn"] += fn

    rows = []
    for class_id, class_name in class_id_to_name.items():
        tp = stats[class_id]["tp"]
        fp = stats[class_id]["fp"]
        fn = stats[class_id]["fn"]

        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1 = (
            2 * precision * recall / (precision + recall)
            if (precision + recall) > 0 else 0.0
        )

        rows.append({
            "class_id": class_id,
            "class_name": class_name,
            "tp": tp,
            "fp": fp,
            "fn": fn,
            "precision": precision,
            "recall": recall,
            "f1": f1,
        })

    return rows

def print_map_results(results, class_id_to_name):
    print("\n===== Overall mAP Metrics =====")
    for key, value in results.items():
        if torch.is_tensor(value):
            if value.numel() == 1:
                print(f"{key}: {value.item():.4f}")
            else:
                print(f"{key}: {value.cpu().numpy()}")

    if "classes" in results and "map_per_class" in results:
        print("\n===== Per-Class mAP =====")
        classes = results["classes"].cpu().tolist()
        map_per_class = results["map_per_class"].cpu().tolist()
        mar_100_per_class = results["mar_100_per_class"].cpu().tolist()

        for cls_id, cls_map, cls_mar in zip(classes, map_per_class, mar_100_per_class):
            class_name = class_id_to_name.get(cls_id, str(cls_id))
            print(
                f"{class_name}: "
                f"mAP={cls_map:.4f}, "
                f"mAR@100={cls_mar:.4f}"
            )


def print_classwise_results(rows):
    print("\n===== Class-wise Precision / Recall / F1 =====")
    for row in rows:
        print(
            f"{row['class_name']}: "
            f"TP={row['tp']} | FP={row['fp']} | FN={row['fn']} | "
            f"Precision={row['precision']:.4f} | "
            f"Recall={row['recall']:.4f} | "
            f"F1={row['f1']:.4f}"
        )

@torch.no_grad()
def visualize_predictions(
    model,
    dataset,
    device,
    num_images=3,
    score_thresh=0.5
):
    model.eval()

    class_colors = {
        1: "lime",    # dead
        2: "red",   # live
    }

    for idx in range(min(num_images, len(dataset))):
        image, target = dataset[idx]

        output = model([image.to(device)])[0]

        pred_boxes = output["boxes"].detach().cpu().numpy()
        pred_scores = output["scores"].detach().cpu().numpy()
        pred_labels = output["labels"].detach().cpu().numpy()

        keep = pred_scores >= score_thresh
        pred_boxes = pred_boxes[keep]
        pred_scores = pred_scores[keep]
        pred_labels = pred_labels[keep]

        image_np = image.cpu().permute(1, 2, 0).numpy()

        plt.figure(figsize=(8, 8))
        plt.imshow(image_np)
        plt.axis("off")
        plt.title(f"Sample {idx}")

        ax = plt.gca()

        for box, score, label in zip(pred_boxes, pred_scores, pred_labels):
            xmin, ymin, xmax, ymax = box
            color = class_colors.get(int(label), "yellow")
            class_name = CLASS_ID_TO_NAME.get(int(label), str(label))

            rect = plt.Rectangle(
                (xmin, ymin),
                xmax - xmin,
                ymax - ymin,
                fill=False,
                edgecolor=color,
                linewidth=2
            )
            ax.add_patch(rect)

            ax.text(
                xmin,
                max(ymin - 5, 0),
                f"{class_name} {score:.2f}",
                color="white",
                fontsize=10,
                bbox=dict(facecolor=color, alpha=0.7, pad=1, edgecolor="none")
            )

        plt.show()

best_map50 = -1.0
history = {
    "train_loss": [],
    "val_map": [],
    "val_map50": [],
}

for epoch in range(NUM_EPOCHS):
    print(f"\nEpoch [{epoch + 1}/{NUM_EPOCHS}]")

    train_loss = train_one_epoch(model, train_loader, optimizer, DEVICE)
    val_results = evaluate_map(model, val_loader, DEVICE)

    train_loss_val = float(train_loss)
    val_map = val_results["map"].item()
    val_map50 = val_results["map_50"].item()

    history["train_loss"].append(train_loss_val)
    history["val_map"].append(val_map)
    history["val_map50"].append(val_map50)

    print(f"Train Loss: {train_loss_val:.4f}")
    print(f"Val mAP:    {val_map:.4f}")
    print(f"Val mAP@50: {val_map50:.4f}")

    if val_map50 > best_map50:
        best_map50 = val_map50
        torch.save(model.state_dict(), MODEL_SAVE_PATH)
        print(f"Saved best model to: {MODEL_SAVE_PATH}")

    scheduler.step()

model.load_state_dict(torch.load(MODEL_SAVE_PATH, map_location=DEVICE))
model.to(DEVICE)
print(f"Loaded best model from: {MODEL_SAVE_PATH}")

test_map_results = evaluate_map(model, test_loader, DEVICE)
print_map_results(test_map_results, CLASS_ID_TO_NAME)

test_classwise_rows = evaluate_classwise_metrics(
    model=model,
    loader=test_loader,
    device=DEVICE,
    iou_thresh=0.5,
    score_thresh=0.5,
    class_id_to_name=CLASS_ID_TO_NAME
)
print_classwise_results(test_classwise_rows)

plt.figure(figsize=(8, 5))
plt.plot(history["train_loss"], label="Train Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss")
plt.legend()
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(history["val_map"], label="Val mAP")
plt.plot(history["val_map50"], label="Val mAP@50")
plt.xlabel("Epoch")
plt.ylabel("Metric")
plt.title("Validation Detection Metrics")
plt.legend()
plt.show()

visualize_predictions(
    model=model,
    dataset=test_dataset,
    device=DEVICE,
    num_images=5,
    score_thresh=0.5
)