# -*- coding: utf-8 -*-
"""finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_eZ5O5PqpVHU0ytAbl6cdcHLCQP9676o
"""

!pip install torchmetrics

"""Notebook-friendly Faster R-CNN fine-tuning with replay sampling.

This module is intentionally organized with `# %%` cell markers so you can
copy sections into separate notebook cells while still keeping the code easy to
turn into a future FastAPI job function.
"""

# %%
# Imports

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable
import copy
import random
import time
import xml.etree.ElementTree as ET

import albumentations as A
import numpy as np
import torch
from albumentations.pytorch import ToTensorV2
from PIL import Image
from torch.utils.data import ConcatDataset, DataLoader, Dataset, Subset
from torchmetrics.detection.mean_ap import MeanAveragePrecision
from torchvision.models.detection import fasterrcnn_resnet50_fpn_v2
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.ops import box_iou
from tqdm.auto import tqdm

try:
    import pandas as pd
except ImportError:  # pragma: no cover - optional dependency for notebooks
    pd = None


# %%
# Configuration


@dataclass(slots=True)
class FineTuneConfig:
    train_dir: Path
    test_dir: Path
    new_dir: Path
    old_model_path: Path
    class_name_to_id: dict[str, int]
    image_size: int = 640
    num_epochs: int = 5
    learning_rate: float = 1e-4
    weight_decay: float = 1e-4
    batch_size: int = 4
    num_workers: int = 0
    seed: int = 42
    freeze_backbone: bool = True
    score_threshold: float = 0.50
    iou_threshold: float = 0.50

    @property
    def num_classes(self) -> int:
        return len(self.class_name_to_id) + 1


# %%
# Utilities


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def choose_device() -> torch.device:
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def collate_fn(batch: list[tuple[torch.Tensor, dict[str, torch.Tensor]]]) -> tuple:
    return tuple(zip(*batch))


def validate_paths(config: FineTuneConfig) -> None:
    required_dirs = [
        config.train_dir,
        config.test_dir,
        config.new_dir,
    ]
    for directory in required_dirs:
        if not directory.exists():
            raise FileNotFoundError(f"Missing directory: {directory}")
        images_dir = directory / "images"
        labels_dir = directory / "labels"
        if not images_dir.exists():
            raise FileNotFoundError(f"Missing images directory: {images_dir}")
        if not labels_dir.exists():
            raise FileNotFoundError(f"Missing labels directory: {labels_dir}")
    if not config.old_model_path.is_file():
        raise FileNotFoundError(f"Missing model checkpoint: {config.old_model_path}")


def image_stems_in_dir(root_dir: Path) -> set[str]:
    valid_exts = {".jpg", ".jpeg", ".png", ".bmp"}
    return {
        path.stem
        for path in root_dir.iterdir()
        if path.is_file() and path.suffix.lower() in valid_exts
    }


def assert_no_data_leakage(config: FineTuneConfig) -> None:
    old_train_stems = image_stems_in_dir(config.train_dir / "images")
    test_stems = image_stems_in_dir(config.test_dir / "images")
    new_stems = image_stems_in_dir(config.new_dir / "images")

    overlaps = {
        "old_train vs test": old_train_stems & test_stems,
        "new_data vs test": new_stems & test_stems,
    }
    leaked = {name: stems for name, stems in overlaps.items() if stems}
    if leaked:
        overlap_summary = ", ".join(
            f"{name} ({len(stems)} overlaps)" for name, stems in leaked.items()
        )
        raise ValueError(
            "Potential data leakage detected between training and test folders: "
            f"{overlap_summary}"
        )


def sample_indices(total_size: int, sample_size: int, seed: int) -> list[int]:
    if sample_size > total_size:
        raise ValueError(f"Requested {sample_size} samples, but only {total_size} exist.")
    rng = random.Random(seed)
    return rng.sample(range(total_size), sample_size)


def recommend_replay_size(
    num_new_samples: int,
    old_train_size: int,
) -> int:
    """Use a simple 1:1 replay policy based on the new-data subset size."""
    if old_train_size <= 0:
        return 0

    return min(old_train_size, max(1, num_new_samples))


def maybe_to_dataframe(records: list[dict[str, Any]]) -> Any:
    if pd is None:
        return records
    return pd.DataFrame(records)


# %%
# Pascal VOC parsing and dataset


def parse_voc_xml(xml_path: Path, class_name_to_id: dict[str, int]) -> tuple[list[list[float]], list[int]]:
    tree = ET.parse(xml_path)
    root = tree.getroot()

    boxes: list[list[float]] = []
    labels: list[int] = []

    for obj in root.findall("object"):
        class_node = obj.find("name")
        bbox_node = obj.find("bndbox")
        if class_node is None or bbox_node is None:
            continue

        class_name = class_node.text.strip().lower()
        if class_name not in class_name_to_id:
            continue

        xmin = float(bbox_node.find("xmin").text)
        ymin = float(bbox_node.find("ymin").text)
        xmax = float(bbox_node.find("xmax").text)
        ymax = float(bbox_node.find("ymax").text)

        if xmax <= xmin or ymax <= ymin:
            continue

        boxes.append([xmin, ymin, xmax, ymax])
        labels.append(class_name_to_id[class_name])

    return boxes, labels


class VOCDataset(Dataset):
    def __init__(
        self,
        images_dir: Path,
        labels_dir: Path,
        class_name_to_id: dict[str, int],
        transforms: A.Compose | None = None,
    ) -> None:
        self.images_dir = Path(images_dir)
        self.labels_dir = Path(labels_dir)
        self.class_name_to_id = class_name_to_id
        self.transforms = transforms
        valid_exts = {".jpg", ".jpeg", ".png", ".bmp"}

        self.samples: list[tuple[Path, Path]] = []
        for image_path in sorted(self.images_dir.iterdir()):
            if image_path.suffix.lower() not in valid_exts:
                continue
            xml_path = self.labels_dir / f"{image_path.stem}.xml"
            if xml_path.exists():
                self.samples.append((image_path, xml_path))

        print(f"Loaded {len(self.samples)} samples from {self.images_dir}")

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, index: int) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
        image_path, xml_path = self.samples[index]
        image_np = np.array(Image.open(image_path).convert("RGB"))
        boxes, labels = parse_voc_xml(xml_path, self.class_name_to_id)

        boxes_np = np.array(boxes, dtype=np.float32) if boxes else np.zeros((0, 4), dtype=np.float32)
        labels_np = np.array(labels, dtype=np.int64) if labels else np.zeros((0,), dtype=np.int64)

        if self.transforms is not None:
            transformed = self.transforms(
                image=image_np,
                bboxes=boxes_np.tolist(),
                labels=labels_np.tolist(),
            )
            image = transformed["image"]
            boxes_np = (
                np.array(transformed["bboxes"], dtype=np.float32)
                if transformed["bboxes"]
                else np.zeros((0, 4), dtype=np.float32)
            )
            labels_np = (
                np.array(transformed["labels"], dtype=np.int64)
                if transformed["labels"]
                else np.zeros((0,), dtype=np.int64)
            )
        else:
            image = ToTensorV2()(image=image_np)["image"]

        image = image.float()
        if image.max() > 1.0:
            image = image / 255.0

        boxes_tensor = torch.as_tensor(boxes_np, dtype=torch.float32)
        labels_tensor = torch.as_tensor(labels_np, dtype=torch.int64)
        area_tensor = (
            (boxes_tensor[:, 2] - boxes_tensor[:, 0]) * (boxes_tensor[:, 3] - boxes_tensor[:, 1])
            if len(boxes_tensor) > 0
            else torch.zeros((0,), dtype=torch.float32)
        )

        target = {
            "boxes": boxes_tensor,
            "labels": labels_tensor,
            "image_id": torch.tensor([index], dtype=torch.int64),
            "area": area_tensor,
            "iscrowd": torch.zeros((len(labels_tensor),), dtype=torch.int64),
        }
        return image, target


# %%
# Transforms and loaders


def get_train_transforms(image_size: int) -> A.Compose:
    return A.Compose(
        [
            A.Resize(height=image_size, width=image_size),
            A.HorizontalFlip(p=0.5),
            A.Rotate(limit=15, p=0.5, border_mode=0),
            A.RandomBrightnessContrast(p=0.3),
            A.Affine(scale=(0.95, 1.05), translate_percent=(0.0, 0.05), p=0.3),
            ToTensorV2(),
        ],
        bbox_params=A.BboxParams(
            format="pascal_voc",
            label_fields=["labels"],
            min_visibility=0.1,
        ),
    )


def get_eval_transforms(image_size: int) -> A.Compose:
    return A.Compose(
        [
            A.Resize(height=image_size, width=image_size),
            ToTensorV2(),
        ],
        bbox_params=A.BboxParams(
            format="pascal_voc",
            label_fields=["labels"],
            min_visibility=0.0,
        ),
    )


def build_datasets(config: FineTuneConfig) -> dict[str, Dataset]:
    train_tfms = get_train_transforms(config.image_size)
    eval_tfms = get_eval_transforms(config.image_size)
    return {
        "old_train": VOCDataset(
            images_dir=config.train_dir / "images",
            labels_dir=config.train_dir / "labels",
            class_name_to_id=config.class_name_to_id,
            transforms=train_tfms,
        ),
        "test": VOCDataset(
            images_dir=config.test_dir / "images",
            labels_dir=config.test_dir / "labels",
            class_name_to_id=config.class_name_to_id,
            transforms=eval_tfms,
        ),
        "new_train": VOCDataset(
            images_dir=config.new_dir / "images",
            labels_dir=config.new_dir / "labels",
            class_name_to_id=config.class_name_to_id,
            transforms=train_tfms,
        ),
    }


def build_train_dataset(
    old_train_dataset: Dataset,
    new_train_dataset: Dataset,
    num_new_samples: int,
    config: FineTuneConfig,
) -> tuple[Dataset, dict[str, Any]]:
    new_indices = sample_indices(len(new_train_dataset), num_new_samples, config.seed)
    replay_size = recommend_replay_size(num_new_samples, len(old_train_dataset))
    replay_indices = sample_indices(len(old_train_dataset), replay_size, config.seed + 1)

    new_subset = Subset(new_train_dataset, new_indices)
    replay_subset = Subset(old_train_dataset, replay_indices)
    train_dataset = ConcatDataset([new_subset, replay_subset])

    subset_summary = {
        "num_new_samples": num_new_samples,
        "replay_size": replay_size,
        "total_train_samples": len(train_dataset),
        "new_indices": new_indices,
        "replay_indices": replay_indices,
    }
    return train_dataset, subset_summary


def build_dataloaders(
    train_dataset: Dataset,
    test_dataset: Dataset,
    config: FineTuneConfig,
) -> tuple[DataLoader, DataLoader]:
    train_loader = DataLoader(
        train_dataset,
        batch_size=config.batch_size,
        shuffle=True,
        num_workers=config.num_workers,
        collate_fn=collate_fn,
    )
    test_loader = DataLoader(
        test_dataset,
        batch_size=config.batch_size,
        shuffle=False,
        num_workers=config.num_workers,
        collate_fn=collate_fn,
    )
    return train_loader, test_loader


# %%
# Model helpers


def create_model(num_classes: int) -> torch.nn.Module:
    model = fasterrcnn_resnet50_fpn_v2(weights=None, weights_backbone=None)
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
    return model


def load_model_from_checkpoint(config: FineTuneConfig, device: torch.device) -> torch.nn.Module:
    model = create_model(config.num_classes)
    state_dict = torch.load(config.old_model_path, map_location=device)
    model.load_state_dict(state_dict)
    model.to(device)
    return model


def configure_trainable_parameters(model: torch.nn.Module, freeze_backbone: bool) -> list[torch.nn.Parameter]:
    if freeze_backbone:
        for parameter in model.backbone.parameters():
            parameter.requires_grad = False
    else:
        for parameter in model.parameters():
            parameter.requires_grad = True
    return [parameter for parameter in model.parameters() if parameter.requires_grad]


# %%
# Training and evaluation


def move_batch_to_device(
    images: Iterable[torch.Tensor],
    targets: Iterable[dict[str, torch.Tensor]],
    device: torch.device,
) -> tuple[list[torch.Tensor], list[dict[str, torch.Tensor]]]:
    image_list = [image.to(device) for image in images]
    target_list = [{key: value.to(device) for key, value in target.items()} for target in targets]
    return image_list, target_list


def train_one_epoch(
    model: torch.nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
) -> float:
    model.train()
    running_loss = 0.0

    progress = tqdm(loader, desc="Training", leave=False)
    for images, targets in progress:
        images, targets = move_batch_to_device(images, targets, device)
        loss_dict = model(images, targets)
        total_loss = sum(loss for loss in loss_dict.values())

        optimizer.zero_grad()
        total_loss.backward()
        optimizer.step()

        running_loss += total_loss.item()
        progress.set_postfix(loss=f"{total_loss.item():.4f}")

    return running_loss / max(len(loader), 1)


@torch.no_grad()
def compute_detection_loss(
    model: torch.nn.Module,
    loader: DataLoader,
    device: torch.device,
) -> float:
    """Compute detection loss on held-out data without optimizer updates.

    Torchvision detection models only return losses in training mode. We switch
    modes temporarily, keep gradients disabled, and restore the original mode.
    """
    was_training = model.training
    model.train()
    running_loss = 0.0

    for images, targets in loader:
        images, targets = move_batch_to_device(images, targets, device)
        loss_dict = model(images, targets)
        total_loss = sum(loss for loss in loss_dict.values())
        running_loss += total_loss.item()

    model.train(was_training)
    return running_loss / max(len(loader), 1)


@torch.no_grad()
def compute_detection_metrics(
    model: torch.nn.Module,
    loader: DataLoader,
    device: torch.device,
    score_threshold: float,
    iou_threshold: float,
) -> dict[str, float]:
    model.eval()
    map_metric = MeanAveragePrecision(
        box_format="xyxy",
        iou_type="bbox",
        class_metrics=False,
    ).to(device)

    total_tp = 0
    total_fp = 0
    total_fn = 0

    progress = tqdm(loader, desc="Evaluating", leave=False)
    for images, targets in progress:
        images, targets = move_batch_to_device(images, targets, device)
        outputs = model(images)

        preds_for_map = []
        gts_for_map = []

        for output, target in zip(outputs, targets):
            preds_for_map.append(
                {
                    "boxes": output["boxes"].detach(),
                    "scores": output["scores"].detach(),
                    "labels": output["labels"].detach(),
                }
            )
            gts_for_map.append(
                {
                    "boxes": target["boxes"].detach(),
                    "labels": target["labels"].detach(),
                }
            )

            filtered = output["scores"] >= score_threshold
            pred_boxes = output["boxes"][filtered].detach().cpu()
            pred_labels = output["labels"][filtered].detach().cpu()
            gt_boxes = target["boxes"].detach().cpu()
            gt_labels = target["labels"].detach().cpu()

            image_tp, image_fp, image_fn = match_detections(
                pred_boxes,
                pred_labels,
                gt_boxes,
                gt_labels,
                iou_threshold,
            )
            total_tp += image_tp
            total_fp += image_fp
            total_fn += image_fn

        map_metric.update(preds_for_map, gts_for_map)

    map_results = map_metric.compute()
    precision = total_tp / (total_tp + total_fp) if (total_tp + total_fp) > 0 else 0.0
    recall = total_tp / (total_tp + total_fn) if (total_tp + total_fn) > 0 else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0

    return {
        "map": float(map_results["map"].item()),
        "map_50": float(map_results["map_50"].item()),
        "map_75": float(map_results["map_75"].item()),
        "mar_100": float(map_results["mar_100"].item()),
        "precision": float(precision),
        "recall": float(recall),
        "f1": float(f1),
    }


def match_detections(
    pred_boxes: torch.Tensor,
    pred_labels: torch.Tensor,
    gt_boxes: torch.Tensor,
    gt_labels: torch.Tensor,
    iou_threshold: float,
) -> tuple[int, int, int]:
    if len(pred_boxes) == 0 and len(gt_boxes) == 0:
        return 0, 0, 0
    if len(pred_boxes) == 0:
        return 0, 0, len(gt_boxes)
    if len(gt_boxes) == 0:
        return 0, len(pred_boxes), 0

    matched_pred: set[int] = set()
    matched_gt: set[int] = set()

    unique_labels = sorted(set(gt_labels.tolist()) | set(pred_labels.tolist()))
    for class_id in unique_labels:
        pred_mask = pred_labels == class_id
        gt_mask = gt_labels == class_id

        class_pred_boxes = pred_boxes[pred_mask]
        class_gt_boxes = gt_boxes[gt_mask]
        pred_indices = pred_mask.nonzero(as_tuple=False).flatten().tolist()
        gt_indices = gt_mask.nonzero(as_tuple=False).flatten().tolist()

        if len(class_pred_boxes) == 0 or len(class_gt_boxes) == 0:
            continue

        ious = box_iou(class_pred_boxes, class_gt_boxes)
        candidate_matches: list[tuple[float, int, int]] = []
        for pred_pos in range(ious.shape[0]):
            for gt_pos in range(ious.shape[1]):
                iou_value = float(ious[pred_pos, gt_pos].item())
                if iou_value >= iou_threshold:
                    candidate_matches.append((iou_value, pred_indices[pred_pos], gt_indices[gt_pos]))

        candidate_matches.sort(reverse=True, key=lambda row: row[0])
        for _, pred_index, gt_index in candidate_matches:
            if pred_index not in matched_pred and gt_index not in matched_gt:
                matched_pred.add(pred_index)
                matched_gt.add(gt_index)

    tp = len(matched_pred)
    fp = len(pred_boxes) - tp
    fn = len(gt_boxes) - len(matched_gt)
    return tp, fp, fn


def evaluate_model(
    model: torch.nn.Module,
    loader: DataLoader,
    device: torch.device,
    config: FineTuneConfig,
) -> dict[str, float]:
    metrics = compute_detection_metrics(
        model=model,
        loader=loader,
        device=device,
        score_threshold=config.score_threshold,
        iou_threshold=config.iou_threshold,
    )
    metrics["loss"] = compute_detection_loss(model=model, loader=loader, device=device)
    return metrics


# %%
# Experiment runners


def run_single_finetuning_experiment(
    config: FineTuneConfig,
    num_new_samples: int,
) -> dict[str, Any]:
    validate_paths(config)
    assert_no_data_leakage(config)
    set_seed(config.seed)

    device = choose_device()
    print(f"\nNow running fine-tuning with {num_new_samples} new samples")
    print(f"Using device: {device}")

    datasets = build_datasets(config)
    train_dataset, subset_summary = build_train_dataset(
        old_train_dataset=datasets["old_train"],
        new_train_dataset=datasets["new_train"],
        num_new_samples=num_new_samples,
        config=config,
    )
    print(
        "Training split summary: "
        f"{subset_summary['num_new_samples']} new + "
        f"{subset_summary['replay_size']} replay = "
        f"{subset_summary['total_train_samples']} total samples"
    )

    train_loader, test_loader = build_dataloaders(
        train_dataset=train_dataset,
        test_dataset=datasets["test"],
        config=config,
    )
    print(f"Batch size: {config.batch_size}")
    print("Evaluating the old checkpoint model on the held-out test set before fine-tuning...")

    baseline_model = load_model_from_checkpoint(config, device)
    baseline_metrics = evaluate_model(baseline_model, test_loader, device, config)
    print(
        "Old model test metrics: "
        f"loss={baseline_metrics['loss']:.4f}, "
        f"mAP@50={baseline_metrics['map_50']:.4f}, "
        f"precision={baseline_metrics['precision']:.4f}, "
        f"recall={baseline_metrics['recall']:.4f}, "
        f"f1={baseline_metrics['f1']:.4f}"
    )

    finetune_model = copy.deepcopy(baseline_model)
    trainable_parameters = configure_trainable_parameters(
        finetune_model,
        freeze_backbone=config.freeze_backbone,
    )
    optimizer = torch.optim.AdamW(
        trainable_parameters,
        lr=config.learning_rate,
        weight_decay=config.weight_decay,
    )

    epoch_history: list[dict[str, Any]] = []
    total_start = time.perf_counter()

    for epoch in range(1, config.num_epochs + 1):
        epoch_start = time.perf_counter()
        train_loss = train_one_epoch(finetune_model, train_loader, optimizer, device)
        test_metrics = evaluate_model(finetune_model, test_loader, device, config)
        epoch_seconds = time.perf_counter() - epoch_start

        epoch_history.append(
            {
                "epoch": epoch,
                "train_loss": train_loss,
                "test_loss": test_metrics["loss"],
                "test_map": test_metrics["map"],
                "test_map_50": test_metrics["map_50"],
                "test_map_75": test_metrics["map_75"],
                "test_mar_100": test_metrics["mar_100"],
                "test_precision": test_metrics["precision"],
                "test_recall": test_metrics["recall"],
                "test_f1": test_metrics["f1"],
                "epoch_seconds": epoch_seconds,
            }
        )

        print(
            f"Epoch {epoch}/{config.num_epochs} | "
            f"train_loss={train_loss:.4f} | "
            f"test_loss={test_metrics['loss']:.4f} | "
            f"test_map50={test_metrics['map_50']:.4f} | "
            f"time={epoch_seconds:.2f}s"
        )

    total_seconds = time.perf_counter() - total_start

    final_metrics = epoch_history[-1].copy() if epoch_history else {}
    return {
        "config": asdict(config),
        "device": str(device),
        "subset_summary": subset_summary,
        "baseline_test_metrics": baseline_metrics,
        "epoch_history": epoch_history,
        "final_epoch_metrics": final_metrics,
        "total_seconds": total_seconds,
        "saved_model_path": None,
        "notes": (
            "Test metrics are logged each epoch for comparison, but they are not "
            "used for checkpoint selection to reduce test-set leakage. "
            "Model weights are not saved in this testing version."
        ),
    }


def benchmark_new_data_sizes(
    config: FineTuneConfig,
    new_sample_sizes: list[int],
) -> dict[str, Any]:
    datasets = build_datasets(config)
    max_available = len(datasets["new_train"])
    requested_sizes = []
    for sample_size in new_sample_sizes:
        if sample_size > max_available:
            raise ValueError(
                f"Requested {sample_size} new images, but only {max_available} are available."
            )
        requested_sizes.append(sample_size)

    experiments: list[dict[str, Any]] = []
    summary_rows: list[dict[str, Any]] = []

    for sample_size in requested_sizes:
        print("\n" + "=" * 80)
        print(f"Starting experiment for {sample_size} new images")
        print("=" * 80)
        result = run_single_finetuning_experiment(config=config, num_new_samples=sample_size)
        experiments.append(result)

        baseline = result["baseline_test_metrics"]
        final_epoch = result["final_epoch_metrics"]
        summary_rows.append(
            {
                "num_new_samples": sample_size,
                "replay_size": result["subset_summary"]["replay_size"],
                "total_train_samples": result["subset_summary"]["total_train_samples"],
                "device": result["device"],
                "baseline_test_loss": baseline["loss"],
                "baseline_map_50": baseline["map_50"],
                "baseline_precision": baseline["precision"],
                "baseline_recall": baseline["recall"],
                "baseline_f1": baseline["f1"],
                "final_test_loss": final_epoch.get("test_loss"),
                "final_map_50": final_epoch.get("test_map_50"),
                "final_precision": final_epoch.get("test_precision"),
                "final_recall": final_epoch.get("test_recall"),
                "final_f1": final_epoch.get("test_f1"),
                "total_seconds": result["total_seconds"],
            }
        )
        print(
            f"Finished run for {sample_size} new images in "
            f"{result['total_seconds']:.2f} seconds"
        )

    return {
        "experiments": experiments,
        "summary": maybe_to_dataframe(summary_rows),
    }


# %%
# Example notebook usage


CLASS_NAME_TO_ID = {
    "live": 1,
    "dead": 2,
}

# Colab setup:
from google.colab import drive
drive.mount("/content/drive")

TEST_DIR = Path("/content/drive/MyDrive/Capstone/Mussel Dataset 1 - RCNN_SSD/test")
TRAIN_DIR = Path("/content/drive/MyDrive/Capstone/Mussel Dataset 1 - RCNN_SSD/train")
NEW_DIR = Path("/content/drive/MyDrive/Capstone/Mussel Dataset 1 - RCNN_SSD/new")
OLD_MODEL_PATH = Path("/content/drive/MyDrive/Capstone/Mussel Dataset 1 - RCNN_SSD/fasterrcnn_best.pth")

CONFIG = FineTuneConfig(
    train_dir=TRAIN_DIR,
    test_dir=TEST_DIR,
    new_dir=NEW_DIR,
    old_model_path=OLD_MODEL_PATH,
    class_name_to_id=CLASS_NAME_TO_ID,
    num_epochs=5,
    seed=42,
)

NUM_NEW_SAMPLES_LIST = [10, 20, 30, 40, 50]


if __name__ == "__main__":
    benchmark_result = benchmark_new_data_sizes(CONFIG, new_sample_sizes=NUM_NEW_SAMPLES_LIST)
    benchmark_result["summary"]