# -*- coding: utf-8 -*-
"""model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138iN6yJ1FAKhipb-JxtO_JC2NlgRJxOq

# Faster R-CNN Training Notebook

# **Read this before you run anything**

# This notebook expects the exact Roboflow dataset zip file.

# What you need to do:
 - Download your labeled dataset from Roboflow to your computer (**see Roboflow guide in Videos/Manuals folder**)
 - Rename the zip file to **Data.zip**  exactly (case-sensitive)
 - Click the **arrow** next to the RAM disk icon in the top right corner of the page. This is directly under the **Share** button.
 - Click **Change Runtime Type**
 - Select **T4 GPU** and then click **Save**
 - Click **Runtime** -> **Run all**.
 - Go to the bottom of the page to see progress
 - It will prompt you to **choose a file**. Choose your newly renamed **Data.zip** file
 - The program will generate progress bars to communicate how much time in remaining

# When the code finishes running
 - The program will automatically download the **model.pth** to your computer
 - Rename the file to describe the model you created. Example: If yor model is trained on juvenile Pocketbook mussels, you could name the model **juvenile_pocketbook.pth**

# What you do with the model file
 - Upload the model to the "Add Model" button on the app

# Video directions of this process can be found in the Videos/Manuals folder of this Shared Google Drive
"""

import subprocess
import sys

subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q", "albumentations", "torchmetrics"],
    check=True,
)


import random
import shutil
import xml.etree.ElementTree as ET
from pathlib import Path
from zipfile import ZipFile

import albumentations as A
import numpy as np
import torch

from albumentations.pytorch import ToTensorV2
from google.colab import files
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchmetrics.detection.mean_ap import MeanAveragePrecision
from torchvision.models.detection import (
    FasterRCNN_ResNet50_FPN_V2_Weights,
    fasterrcnn_resnet50_fpn_v2,
)
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.ops import box_iou
from tqdm.auto import tqdm


DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
NUM_CLASSES = 3  # background + live + dead

CLASS_NAME_TO_ID = {
    "live": 1,
    "dead": 2,
}

CLASS_ID_TO_NAME = {
    1: "live",
    2: "dead",
}

SEED = 42
BATCH_SIZE = 8
NUM_WORKERS = 0
NUM_EPOCHS = 10
LR = 1e-4
WEIGHT_DECAY = 5e-4
GRAD_CLIP_NORM = 5.0
IMAGE_SIZE = 896
TRAIN_AFFINE_P = 0.25
TRAIN_BLUR_P = 0.10
TRAIN_BRIGHTNESS_P = 0.30
TEST_SCORE_THRESH = 0.25

MODEL_SAVE_PATH = Path("/content/model.pth")
EXTRACT_ROOT = Path("/content/Data")

def collate_fn(batch):
    return tuple(zip(*batch))


def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


set_seed(SEED)


def upload_and_extract_dataset():
    print("Step 1 of 4: Please upload Data.zip now.")
    uploaded = files.upload()

    zip_names = [name for name in uploaded.keys() if name.lower().endswith(".zip")]
    if len(zip_names) != 1:
        raise ValueError("Please upload exactly one zip file named Data.zip.")

    zip_name = zip_names[0]
    if Path(zip_name).stem != "Data":
        raise ValueError("The uploaded file must be named Data.zip exactly.")

    zip_path = Path(f"/content/{zip_name}")

    if EXTRACT_ROOT.exists():
        shutil.rmtree(EXTRACT_ROOT)
    EXTRACT_ROOT.mkdir(parents=True, exist_ok=True)

    with ZipFile(zip_path, "r") as zip_file:
        zip_file.extractall(EXTRACT_ROOT)

    extracted_dirs = [path for path in EXTRACT_ROOT.iterdir() if path.is_dir()]
    extracted_files = [path for path in EXTRACT_ROOT.iterdir() if path.is_file()]

    if len(extracted_dirs) == 1 and not extracted_files:
        dataset_root = extracted_dirs[0]
    else:
        dataset_root = EXTRACT_ROOT

    train_dir = dataset_root / "train"
    test_dir = dataset_root / "test"

    if not train_dir.exists():
        raise ValueError("Could not find a train folder inside Data.zip.")
    if not test_dir.exists():
        raise ValueError("Could not find a test folder inside Data.zip.")

    print("Upload complete.")
    print(f"Using training folder: {train_dir}")
    print(f"Using test folder: {test_dir}")
    return train_dir, test_dir


def parse_voc_xml(xml_path: Path, class_name_to_id: dict):
    tree = ET.parse(xml_path)
    root = tree.getroot()

    boxes = []
    labels = []

    for obj in root.findall("object"):
        name_tag = obj.find("name")
        if name_tag is None or name_tag.text is None:
            continue

        class_name = name_tag.text.strip().lower()
        if class_name not in class_name_to_id:
            continue

        bndbox = obj.find("bndbox")
        if bndbox is None:
            continue

        xmin = float(bndbox.find("xmin").text)
        ymin = float(bndbox.find("ymin").text)
        xmax = float(bndbox.find("xmax").text)
        ymax = float(bndbox.find("ymax").text)

        if xmax <= xmin or ymax <= ymin:
            continue

        boxes.append([xmin, ymin, xmax, ymax])
        labels.append(class_name_to_id[class_name])

    return boxes, labels


def list_samples(split_dir: Path):
    valid_exts = {".jpg", ".jpeg", ".png", ".bmp"}
    image_paths = sorted(
        [path for path in split_dir.iterdir() if path.is_file() and path.suffix.lower() in valid_exts]
    )

    samples = []
    for img_path in image_paths:
        xml_path = split_dir / f"{img_path.stem}.xml"
        if xml_path.exists():
            samples.append((img_path, xml_path))

    if not samples:
        raise ValueError(f"No valid image/XML pairs were found in {split_dir}.")

    return samples


def get_train_transforms():
    return A.Compose(
        [
            A.LongestMaxSize(max_size=IMAGE_SIZE),
            A.PadIfNeeded(
                min_height=IMAGE_SIZE,
                min_width=IMAGE_SIZE,
                border_mode=0,
                fill=(114, 114, 114),
            ),
            A.HorizontalFlip(p=0.5),
            A.Affine(
                scale=(0.90, 1.10),
                translate_percent=(-0.05, 0.05),
                rotate=(-12, 12),
                shear=(-5, 5),
                border_mode=0,
                fill=(114, 114, 114),
                p=TRAIN_AFFINE_P,
            ),
            A.OneOf(
                [
                    A.RandomBrightnessContrast(brightness_limit=0.15, contrast_limit=0.15),
                    A.RandomGamma(gamma_limit=(85, 115)),
                    A.CLAHE(clip_limit=2.0, tile_grid_size=(8, 8)),
                ],
                p=TRAIN_BRIGHTNESS_P,
            ),
            A.OneOf(
                [
                    A.GaussNoise(std_range=(0.01, 0.04)),
                    A.MotionBlur(blur_limit=3),
                    A.MedianBlur(blur_limit=3),
                ],
                p=TRAIN_BLUR_P,
            ),
            ToTensorV2(),
        ],
        bbox_params=A.BboxParams(
            format="pascal_voc",
            label_fields=["labels"],
            min_visibility=0.25,
        ),
    )


def get_eval_transforms():
    return A.Compose(
        [
            A.LongestMaxSize(max_size=IMAGE_SIZE),
            A.PadIfNeeded(
                min_height=IMAGE_SIZE,
                min_width=IMAGE_SIZE,
                border_mode=0,
                fill=(114, 114, 114),
            ),
            ToTensorV2(),
        ],
        bbox_params=A.BboxParams(
            format="pascal_voc",
            label_fields=["labels"],
            min_visibility=0.0,
        ),
    )


class VOCDataset(Dataset):
    def __init__(self, samples, class_name_to_id, transforms=None):
        self.samples = list(samples)
        self.class_name_to_id = class_name_to_id
        self.transforms = transforms

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, xml_path = self.samples[idx]

        image = np.array(Image.open(img_path).convert("RGB"))
        boxes, labels = parse_voc_xml(xml_path, self.class_name_to_id)

        boxes_np = np.array(boxes, dtype=np.float32) if boxes else np.zeros((0, 4), dtype=np.float32)
        labels_np = np.array(labels, dtype=np.int64) if labels else np.zeros((0,), dtype=np.int64)

        if self.transforms is not None:
            transformed = self.transforms(
                image=image,
                bboxes=boxes_np.tolist(),
                labels=labels_np.tolist(),
            )
            image = transformed["image"]

            if transformed["bboxes"]:
                boxes_np = np.array(transformed["bboxes"], dtype=np.float32)
                labels_np = np.array(transformed["labels"], dtype=np.int64)
            else:
                boxes_np = np.zeros((0, 4), dtype=np.float32)
                labels_np = np.zeros((0,), dtype=np.int64)
        else:
            image = ToTensorV2()(image=image)["image"]

        if image.dtype != torch.float32:
            image = image.float()

        if image.max() > 1.0:
            image = image / 255.0

        boxes_tensor = torch.as_tensor(boxes_np, dtype=torch.float32)
        labels_tensor = torch.as_tensor(labels_np, dtype=torch.int64)

        area = (
            (boxes_tensor[:, 2] - boxes_tensor[:, 0]) *
            (boxes_tensor[:, 3] - boxes_tensor[:, 1])
        ) if len(boxes_tensor) > 0 else torch.zeros((0,), dtype=torch.float32)

        target = {
            "boxes": boxes_tensor,
            "labels": labels_tensor,
            "image_id": torch.tensor([idx]),
            "area": area,
            "iscrowd": torch.zeros((len(labels_tensor),), dtype=torch.int64),
        }

        return image, target


def create_loader(samples, transforms, shuffle):
    dataset = VOCDataset(
        samples=samples,
        class_name_to_id=CLASS_NAME_TO_ID,
        transforms=transforms,
    )
    return DataLoader(
        dataset,
        batch_size=BATCH_SIZE,
        shuffle=shuffle,
        num_workers=NUM_WORKERS,
        pin_memory=torch.cuda.is_available(),
        collate_fn=collate_fn,
    )


def get_model(num_classes: int):
    weights = FasterRCNN_ResNet50_FPN_V2_Weights.DEFAULT
    model = fasterrcnn_resnet50_fpn_v2(weights=weights)

    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
    return model


def build_optimizer(model):
    params = [parameter for parameter in model.parameters() if parameter.requires_grad]
    return torch.optim.AdamW(params, lr=LR, weight_decay=WEIGHT_DECAY)


def build_scheduler(optimizer):
    return torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=NUM_EPOCHS,
        eta_min=LR / 20.0,
    )


def train_one_epoch(model, loader, optimizer, device):
    model.train()
    running_loss = 0.0
    pbar = tqdm(loader, desc="Training", leave=False)

    for images, targets in pbar:
        images = [img.to(device) for img in images]
        targets = [{key: value.to(device) for key, value in target.items()} for target in targets]

        loss_dict = model(images, targets)
        loss = sum(loss_component for loss_component in loss_dict.values())

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP_NORM)
        optimizer.step()

        running_loss += loss.item()
        pbar.set_postfix(loss=f"{loss.item():.4f}")

    return running_loss / max(len(loader), 1)


@torch.no_grad()
def evaluate_map50(model, loader, device):
    model.eval()

    metric = MeanAveragePrecision(
        box_format="xyxy",
        iou_type="bbox",
        class_metrics=False,
    ).to(device)

    for images, targets in tqdm(loader, desc="Evaluating mAP@50", leave=False):
        images = [img.to(device) for img in images]
        outputs = model(images)

        preds = []
        gts = []

        for output, target in zip(outputs, targets):
            preds.append(
                {
                    "boxes": output["boxes"].detach().to(device),
                    "scores": output["scores"].detach().to(device),
                    "labels": output["labels"].detach().to(device),
                }
            )
            gts.append(
                {
                    "boxes": target["boxes"].to(device),
                    "labels": target["labels"].to(device),
                }
            )

        metric.update(preds, gts)

    results = metric.compute()
    return float(results["map_50"].item())


@torch.no_grad()
def evaluate_classwise_precision_recall(
    model,
    loader,
    device,
    iou_thresh=0.5,
    score_thresh=0.25,
):
    model.eval()

    stats = {
        class_id: {"tp": 0, "fp": 0, "fn": 0}
        for class_id in CLASS_ID_TO_NAME.keys()
    }

    for images, targets in tqdm(loader, desc="Evaluating precision/recall", leave=False):
        images = [img.to(device) for img in images]
        outputs = model(images)

        for output, target in zip(outputs, targets):
            pred_boxes = output["boxes"].detach().cpu()
            pred_scores = output["scores"].detach().cpu()
            pred_labels = output["labels"].detach().cpu()

            gt_boxes = target["boxes"].cpu()
            gt_labels = target["labels"].cpu()

            keep = pred_scores >= score_thresh
            pred_boxes = pred_boxes[keep]
            pred_labels = pred_labels[keep]

            for class_id in CLASS_ID_TO_NAME.keys():
                pred_mask = pred_labels == class_id
                gt_mask = gt_labels == class_id

                cls_pred_boxes = pred_boxes[pred_mask]
                cls_gt_boxes = gt_boxes[gt_mask]

                if len(cls_pred_boxes) == 0 and len(cls_gt_boxes) == 0:
                    continue

                if len(cls_pred_boxes) == 0:
                    stats[class_id]["fn"] += len(cls_gt_boxes)
                    continue

                if len(cls_gt_boxes) == 0:
                    stats[class_id]["fp"] += len(cls_pred_boxes)
                    continue

                ious = box_iou(cls_pred_boxes, cls_gt_boxes)

                matched_gt = set()
                matched_pred = set()
                candidate_pairs = []

                for pred_idx in range(ious.shape[0]):
                    for gt_idx in range(ious.shape[1]):
                        iou_val = ious[pred_idx, gt_idx].item()
                        if iou_val >= iou_thresh:
                            candidate_pairs.append((iou_val, pred_idx, gt_idx))

                candidate_pairs.sort(reverse=True, key=lambda x: x[0])

                for _, pred_idx, gt_idx in candidate_pairs:
                    if pred_idx not in matched_pred and gt_idx not in matched_gt:
                        matched_pred.add(pred_idx)
                        matched_gt.add(gt_idx)

                tp = len(matched_pred)
                fp = len(cls_pred_boxes) - tp
                fn = len(cls_gt_boxes) - len(matched_gt)

                stats[class_id]["tp"] += tp
                stats[class_id]["fp"] += fp
                stats[class_id]["fn"] += fn

    rows = []
    for class_id, class_name in CLASS_ID_TO_NAME.items():
        tp = stats[class_id]["tp"]
        fp = stats[class_id]["fp"]
        fn = stats[class_id]["fn"]

        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0

        rows.append(
            {
                "class_name": class_name,
                "precision": precision,
                "recall": recall,
            }
        )

    return rows


def train_model(train_samples):
    print("\nStep 2 of 4: Preparing training data loader.")
    train_loader = create_loader(train_samples, get_train_transforms(), shuffle=True)

    model = get_model(NUM_CLASSES).to(DEVICE)
    optimizer = build_optimizer(model)
    scheduler = build_scheduler(optimizer)

    print("\nStep 3 of 4: Training the model.")
    epoch_pbar = tqdm(range(NUM_EPOCHS), desc="Overall training progress", unit="epoch")

    for epoch in epoch_pbar:
        epoch_pbar.set_postfix(epoch=f"{epoch + 1}/{NUM_EPOCHS}")
        print(f"\nEpoch [{epoch + 1}/{NUM_EPOCHS}]")
        train_loss = train_one_epoch(model, train_loader, optimizer, DEVICE)
        current_lr = optimizer.param_groups[0]["lr"]

        print(f"Train Loss: {train_loss:.4f}")
        print(f"LR:         {current_lr:.6f}")
        epoch_pbar.set_postfix(
            epoch=f"{epoch + 1}/{NUM_EPOCHS}",
            train_loss=f"{train_loss:.4f}",
        )

        scheduler.step()

    torch.save(model.state_dict(), MODEL_SAVE_PATH)
    print(f"\nSaved trained model to: {MODEL_SAVE_PATH}")
    return model


def print_test_results(map50, classwise_rows):
    print("\nStep 4 of 4: Final test results.")
    print("\n" + "=" * 50)
    print("FINAL TEST RESULTS")
    print("=" * 50)
    print(
        f"Overall detection score (mAP@50): {map50:.4f} "
        f"({map50 * 100:.2f}%)"
    )
    print(
        "Higher is better. This measures how well the model finds and "
        "correctly localizes objects on the test set."
    )
    print("\nPer-class results")
    print("-" * 50)
    for row in classwise_rows:
        precision_pct = row["precision"] * 100.0
        recall_pct = row["recall"] * 100.0
        print(
            f"{row['class_name'].title():<10} "
            f"Precision: {row['precision']:.4f} ({precision_pct:.2f}%) | "
            f"Recall: {row['recall']:.4f} ({recall_pct:.2f}%)"
        )
    print("-" * 50)
    print("Precision means: when the model predicts a class, how often it is correct.")
    print("Recall means: out of the true objects in the test set, how many the model found.")

train_dir, test_dir = upload_and_extract_dataset()
train_samples = list_samples(train_dir)
test_samples = list_samples(test_dir)

print(f"Loaded {len(train_samples)} training images.")
print(f"Loaded {len(test_samples)} test images.")

model = train_model(train_samples)

print("\nPreparing test evaluation.")
test_loader = create_loader(test_samples, get_eval_transforms(), shuffle=False)
test_map50 = evaluate_map50(model, test_loader, DEVICE)
test_classwise_rows = evaluate_classwise_precision_recall(
    model=model,
    loader=test_loader,
    device=DEVICE,
    iou_thresh=0.5,
    score_thresh=TEST_SCORE_THRESH,
)
print_test_results(test_map50, test_classwise_rows)

files.download(str(MODEL_SAVE_PATH))